### PR TITLE
fix: broken ci

### LINKED ISSUE #693: Bug report: CI is broken due to missing types
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

In CLI, do `deno fmt --check && deno lint && deno task check:license --check && deno task check:types && deno task test`.

**Expected behavior** A clear and concise description of what you expected to

All tests should pass.

**Screenshots** If applicable, add screenshots to help explain your problem.

Screenshot 2024-10-25 at 06 02 30

**Desktop (please complete the following information):**

- OS: macOS 15.0.1
- Deno version 2.0.2

### PR DESCRIPTION
**Pull request by dominikj111**
The CI is broken due to various issues, in this request all issues with CI are solved.

Unfortunately I had to cherry-pick the commit https://github.com/denoland/saaskit/pull/692/commits/6c6399bd1b6a8fec351725be1700013d37df17c3 as it was blockage. 

The commands
`deno task build` 
`deno fmt --check && deno lint && deno task check:license --check && deno task check:types && deno task test`
work well on Deno 1.46.3 as well as on 2.0.2

closes #693

### CODE REVIEW

File: e2e_test.ts [hunk 1]
```diff
@@ -881,6 +881,9 @@ Deno.test("[e2e] GET /account/upgrade", async (test) => {
   await createUser(user);
 
   await test.step("serves internal server error response if the `STRIPE_PREMIUM_PLAN_PRICE_ID` environment variable is not set", async () => {
+    // Suppress the error message thrown by the handler
+    const stubbedError = stub(console, "error");
```
Comment (iuioiua) [inline e2e_test.ts:885]:
```suggestion
    using stubbedError = stub(console, "error");
```
Removes the need for `stubbedError.restore();` below.

File: utils/db.ts [hunk 2]
```diff
@@ -1,4 +1,7 @@
 // Copyright 2023-2024 the Deno authors. All rights reserved. MIT license.
+
+/// <reference lib="deno.unstable" />
```
Comment (iuioiua) [inline utils/db.ts:3]: @kt3k shouldn't `"unstable": ["kv"]` within `deno.json` fix this?

**Review by iuioiua — CHANGES_REQUESTED** [review]

**Comment by iuioiua** [comment]
PTAL @kt3k

File: utils/db.ts (hunk 2 above)
Comment (dominikj111) [reply utils/db.ts:3]: Weirdly it didn't. I see there is `--unstable-kv` option provided when running `deno task test`, but same problem. I think it could be some deno issue. I have been able to make it work only with the `reference ... ` comment.

File: e2e_test.ts (hunk 1 above)
Comment (dominikj111) [reply e2e_test.ts:885]: TS doesn't like it
Screenshot 2024-10-31 at 20 01 45

Comment (iuioiua) [reply e2e_test.ts:885]: Ah. Ignore then :)

File: utils/db.ts (hunk 2 above)
Comment (iuioiua) [reply utils/db.ts:3]: Yeah, this seems like a runtime issue.

**Review by kt3k — APPROVED** [review]
LGTM. Thanks for fixing!
