### PR TITLE
fix: active dashboard link

### LINKED ISSUE #469: todo: fix active dashboard link
When the user is on the "Pricing" or "Account" pages, their respective links are indicated as active by being full black (or white in dark mode). However, the "Dashboard" link stays grey when on the dashboard page. The "Dashboard" link should behave like the other 2 header links.

### PR DESCRIPTION
**Pull request by mbhrznr**
closes #469

### CODE REVIEW

File: components/Header.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ export default function Header(
         <a
           href="/dashboard"
           class={cx(
-            props.url.pathname.includes("/dashboard")
+            props.url.pathname.startsWith("/dashboard")
```
Comment (iuioiua) [inline components/Header.tsx:71]: Frankly, I think this is the only change that's needed.

File: components/Header.tsx [hunk 2]
```diff
@@ -81,7 +81,7 @@ export default function Header(
             <a
               href="/pricing"
               class={cx(
-                props.url.pathname === "/pricing"
+                props.url.pathname.startsWith("/pricing")
```
Comment (iuioiua) [inline components/Header.tsx:84]:
```suggestion
                props.url.pathname === "/pricing"
```

File: components/Header.tsx [hunk 3]
```diff
@@ -96,7 +96,7 @@ export default function Header(
             <a
               href="/account"
               class={cx(
-                props.url.pathname === "/account"
+                props.url.pathname.startsWith("/account")
```
Comment (iuioiua) [inline components/Header.tsx:99]:
```suggestion
                props.url.pathname === "/account"
```

File: components/Header.tsx [hunk 4]
```diff
@@ -109,7 +109,7 @@ export default function Header(
         <a
           href="/notifications"
           class={cx(
-            props.url.pathname === "/notifications"
+            props.url.pathname.startsWith("/notifications")
```
Comment (iuioiua) [inline components/Header.tsx:112]:
```suggestion
            props.url.pathname === "/notifications"
```

**Review by iuioiua — CHANGES_REQUESTED** [review]

**Review by iuioiua — APPROVED** [review]
I made a couple of tweaks, and now, LGTM! Thank you.
